import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { CalendarPlus, Play, Pause, Archive, RefreshCw } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';
import { changeScheduleRuleStatus, createScheduleRule, listAdminServices, listScheduleRules, materializeAppointmentSlots, type ScheduleRule, type ScheduleRuleInput, type SlotMaterialization } from './queue-admin.api';

const DAYS = [['MONDAY', 'Segunda-feira'], ['TUESDAY', 'Terça-feira'], ['WEDNESDAY', 'Quarta-feira'], ['THURSDAY', 'Quinta-feira'], ['FRIDAY', 'Sexta-feira'], ['SATURDAY', 'Sábado'], ['SUNDAY', 'Domingo']];
const today = () => new Date().toISOString().slice(0, 10);
const plusDays = (days: number) => { const date = new Date(); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };
const statusLabel: Record<ScheduleRule['status'], string> = { DRAFT: 'Rascunho', ACTIVE: 'Ativa', SUSPENDED: 'Suspensa', RETIRED: 'Retirada' };

export function ScheduleRulesPanel() {
  const rules = useQuery({ queryKey: ['appointment-schedule-rules'], queryFn: listScheduleRules });
  const services = useQuery({ queryKey: ['admin-services'], queryFn: listAdminServices });
  const [serviceId, setServiceId] = useState(''); const [locationCode, setLocationCode] = useState('BOANE'); const [dayOfWeek, setDayOfWeek] = useState('MONDAY');
  const [startLocalTime, setStartLocalTime] = useState('08:00'); const [endLocalTime, setEndLocalTime] = useState('16:00'); const [slotDurationMinutes, setSlotDurationMinutes] = useState(30); const [capacityPerSlot, setCapacityPerSlot] = useState(1);
  const [effectiveFrom, setEffectiveFrom] = useState(today()); const [effectiveUntil, setEffectiveUntil] = useState(''); const [materializeFrom, setMaterializeFrom] = useState(today()); const [materializeTo, setMaterializeTo] = useState(plusDays(30));
  const [materialization, setMaterialization] = useState<SlotMaterialization | null>(null);
  const command = useMutation({ mutationFn: (action: () => Promise<unknown>) => action(), onSuccess: () => rules.refetch() });
  const materialize = useMutation({ mutationFn: () => materializeAppointmentSlots(materializeFrom, materializeTo), onSuccess: setMaterialization });
  const selectedService = services.data?.find((item) => item.id === serviceId);
  const save = () => { if (!selectedService) return; const input: ScheduleRuleInput = { serviceId, departmentId: selectedService.departmentId, locationCode: locationCode.trim(), dayOfWeek, startLocalTime, endLocalTime, slotDurationMinutes, capacityPerSlot, effectiveFrom, effectiveUntil: effectiveUntil || null }; command.mutate(() => createScheduleRule(input)); };
  const transition = (rule: ScheduleRule, status: ScheduleRule['status']) => command.mutate(() => changeScheduleRuleStatus(rule, status));
  const hasError = rules.isError || services.isError || command.isError || materialize.isError;

  return <section className="space-y-5 border-t pt-7" aria-labelledby="schedule-title">
    <div><p className="text-sm font-medium text-primary">Agenda e capacidade</p><h3 id="schedule-title" className="mt-1 text-xl font-semibold">Quando cada serviço pode receber marcações?</h3><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Crie regras em rascunho, valide horários e capacidade, ative-as e só depois gere os slots do período operacional.</p></div>
    {hasError && <Alert variant="destructive"><AlertTitle>Alteração não concluída</AlertTitle><AlertDescription>Revise os dados ou atualize a lista; a regra pode ter sido alterada por outro administrador.</AlertDescription></Alert>}
    {(rules.isLoading || services.isLoading) && <Skeleton className="h-48" />}
    <div className="rounded-lg border bg-card p-5"><h4 className="font-semibold">Nova regra de agenda</h4><div className="mt-4 grid gap-4 tb:grid-cols-2 lg:grid-cols-4">
      <div className="space-y-2 lg:col-span-2"><Label htmlFor="rule-service">Serviço</Label><select id="rule-service" className="min-h-11 w-full rounded-md border bg-background px-3 text-sm" value={serviceId} onChange={(e) => setServiceId(e.target.value)}><option value="">Selecione</option>{services.data?.filter((item) => item.status === 'PUBLISHED').map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>
      <div className="space-y-2"><Label htmlFor="rule-location">Código do local</Label><Input id="rule-location" value={locationCode} maxLength={40} onChange={(e) => setLocationCode(e.target.value.toUpperCase())} /></div>
      <div className="space-y-2"><Label htmlFor="rule-day">Dia da semana</Label><select id="rule-day" className="min-h-11 w-full rounded-md border bg-background px-3 text-sm" value={dayOfWeek} onChange={(e) => setDayOfWeek(e.target.value)}>{DAYS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
      <div className="space-y-2"><Label htmlFor="rule-start">Início</Label><Input id="rule-start" type="time" value={startLocalTime} onChange={(e) => setStartLocalTime(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="rule-end">Fim</Label><Input id="rule-end" type="time" value={endLocalTime} onChange={(e) => setEndLocalTime(e.target.value)} /></div>
      <div className="space-y-2"><Label htmlFor="rule-duration">Duração do slot (min.)</Label><Input id="rule-duration" type="number" min={5} max={480} value={slotDurationMinutes} onChange={(e) => setSlotDurationMinutes(Number(e.target.value))} /></div><div className="space-y-2"><Label htmlFor="rule-capacity">Capacidade por slot</Label><Input id="rule-capacity" type="number" min={1} max={500} value={capacityPerSlot} onChange={(e) => setCapacityPerSlot(Number(e.target.value))} /></div>
      <div className="space-y-2"><Label htmlFor="rule-from">Válida desde</Label><Input id="rule-from" type="date" value={effectiveFrom} onChange={(e) => setEffectiveFrom(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="rule-until">Válida até (opcional)</Label><Input id="rule-until" type="date" min={effectiveFrom} value={effectiveUntil} onChange={(e) => setEffectiveUntil(e.target.value)} /></div>
    </div><Button className="mt-5" disabled={!selectedService || !locationCode.trim() || !startLocalTime || !endLocalTime || !effectiveFrom || command.isPending} onClick={save}><CalendarPlus className="mr-2 size-4" />Guardar rascunho</Button></div>
    <div><h4 className="font-semibold">Regras configuradas</h4><div className="mt-3 space-y-3">{rules.data?.length === 0 && <p className="rounded-lg border border-dashed p-5 text-sm text-muted-foreground">Ainda não existem regras de agenda.</p>}{rules.data?.map((rule) => <article key={rule.id} className="rounded-lg border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{rule.serviceTitle}</p><p className="mt-1 text-sm text-muted-foreground">{DAYS.find(([value]) => value === rule.dayOfWeek)?.[1]} · {rule.startLocalTime.slice(0, 5)}–{rule.endLocalTime.slice(0, 5)} · {rule.slotDurationMinutes} min. · capacidade {rule.capacityPerSlot}</p><p className="mt-1 text-xs text-muted-foreground">{rule.locationCode} · desde {rule.effectiveFrom}{rule.effectiveUntil ? ` até ${rule.effectiveUntil}` : ''}</p></div><Badge variant="outline">{statusLabel[rule.status]}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{(rule.status === 'DRAFT' || rule.status === 'SUSPENDED') && <Button size="sm" variant="outline" disabled={command.isPending} onClick={() => transition(rule, 'ACTIVE')}><Play className="mr-2 size-4" />Ativar</Button>}{rule.status === 'ACTIVE' && <Button size="sm" variant="outline" disabled={command.isPending} onClick={() => transition(rule, 'SUSPENDED')}><Pause className="mr-2 size-4" />Suspender</Button>}{(rule.status === 'DRAFT' || rule.status === 'SUSPENDED') && <Button size="sm" variant="ghost" disabled={command.isPending} onClick={() => transition(rule, 'RETIRED')}><Archive className="mr-2 size-4" />Retirar</Button>}</div></article>)}</div></div>
    <div className="rounded-lg border bg-muted/30 p-5"><h4 className="font-semibold">Gerar slots operacionais</h4><p className="mt-1 text-sm text-muted-foreground">Processa apenas regras ativas. A repetição é segura: slots existentes não são duplicados.</p><div className="mt-4 grid max-w-xl gap-4 xsm:grid-cols-2"><div className="space-y-2"><Label htmlFor="materialize-from">De</Label><Input id="materialize-from" type="date" min={today()} value={materializeFrom} onChange={(e) => setMaterializeFrom(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="materialize-to">Até</Label><Input id="materialize-to" type="date" min={materializeFrom} value={materializeTo} onChange={(e) => setMaterializeTo(e.target.value)} /></div></div><Button className="mt-4" variant="outline" disabled={!materializeFrom || !materializeTo || materialize.isPending} onClick={() => materialize.mutate()}><RefreshCw className="mr-2 size-4" />{materialize.isPending ? 'A gerar…' : 'Gerar slots'}</Button>{materialization && <p className="mt-3 text-sm" role="status"><strong>{materialization.created}</strong> slots criados; {materialization.existing} já existiam.</p>}</div>
  </section>;
}
