import { FormEvent, useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { toast } from 'sonner';
import { CitizenLayout } from '@/components/citizen/CitizenLayout';
import { citizenService } from '@/services/citizen.service';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import type { CitizenProfile } from '@/types';

const empty = { fullName: '', phone: '', nuit: '', documentType: '', documentNumber: '', birthDate: '', gender: '', address: '' };
export default function CitizenPerfil() {
  const [profile, setProfile] = useState<CitizenProfile>(); const [form, setForm] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { citizenService.getProfile().then(result => { if (result.data) { setProfile(result.data); setForm({ fullName: result.data.fullName, phone: result.data.phone ?? '', nuit: result.data.nuit ?? '', documentType: result.data.documentType ?? '', documentNumber: result.data.documentNumber ?? '', birthDate: result.data.birthDate ?? '', gender: result.data.gender ?? '', address: result.data.address ?? '' }); } setError(result.error); setLoading(false); }); }, []);
  const field = (name: keyof typeof empty) => (event: React.ChangeEvent<HTMLInputElement>) => setForm(current => ({ ...current, [name]: event.target.value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const result = await citizenService.updateProfile(form); if (result.data) { setProfile(result.data); toast.success('Dados guardados'); } else toast.error(result.error); setSaving(false); };
  return <CitizenLayout title="Conta" subtitle="Mantenha os seus dados de contacto e identificação atualizados">
    {loading ? <Skeleton className="h-96 max-w-3xl" /> : error && !profile ? <div role="alert" className="border-l-4 border-destructive p-4">{error}</div> : <form onSubmit={submit} className="max-w-3xl space-y-8"><section><h2 className="font-semibold">Acesso</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Email<Input className="mt-1" value={profile?.email ?? ''} disabled /><span className="mt-1 block text-xs font-normal text-muted-foreground">O email de acesso não pode ser alterado aqui.</span></label><label className="text-sm font-medium">Estado do email<Input className="mt-1" value={profile?.emailVerified ? 'Verificado' : 'Por verificar'} disabled /></label></div></section><section className="border-t border-border pt-6"><h2 className="font-semibold">Dados pessoais</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nome completo<Input required maxLength={150} className="mt-1" value={form.fullName} onChange={field('fullName')} /></label><label className="text-sm font-medium">Telefone<Input maxLength={50} className="mt-1" value={form.phone} onChange={field('phone')} /></label><label className="text-sm font-medium">NUIT<Input maxLength={50} className="mt-1" value={form.nuit} onChange={field('nuit')} /></label><label className="text-sm font-medium">Tipo de documento<Input maxLength={50} className="mt-1" value={form.documentType} onChange={field('documentType')} /></label><label className="text-sm font-medium">Número do documento<Input maxLength={80} className="mt-1" value={form.documentNumber} onChange={field('documentNumber')} /></label><label className="text-sm font-medium">Data de nascimento<Input type="date" className="mt-1" value={form.birthDate} onChange={field('birthDate')} /></label><label className="text-sm font-medium">Género<Input maxLength={30} className="mt-1" value={form.gender} onChange={field('gender')} /></label><label className="text-sm font-medium sm:col-span-2">Morada<Input maxLength={1000} className="mt-1" value={form.address} onChange={field('address')} /></label></div></section><Button disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? 'A guardar…' : 'Guardar alterações'}</Button></form>}
  </CitizenLayout>;
}
