import { useMutation, useQuery } from '@tanstack/react-query';
import { CalendarClock, CheckCircle2, RefreshCw } from 'lucide-react';
import { AdminLayout } from '@/components/admin/AdminLayout';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { assistedCheckIn, listAdminAppointments } from '@/features/queue-admin/queue-admin.api';

export default function AdminAgenda() {
  const appointments = useQuery({ queryKey: ['admin-appointments'], queryFn: listAdminAppointments, refetchInterval: () => document.hidden ? false : 20_000 });
  const checkIn = useMutation({ mutationFn: assistedCheckIn, onSuccess: () => appointments.refetch() });
  const ordered = [...(appointments.data || [])].sort((a, b) => Date.parse(a.startTime || '') - Date.parse(b.startTime || ''));
  return <AdminLayout title="Agenda de atendimento" subtitle="Agendamentos e check-in assistido"><div className="mx-auto max-w-[1100px] space-y-6"><header className="border-b pb-5"><p className="text-sm font-medium text-primary">Agenda F5</p><h2 className="mt-1 text-2xl font-semibold">Quem está previsto para atendimento?</h2><p className="mt-2 text-sm text-muted-foreground">Use o check-in assistido apenas quando o munícipe estiver fisicamente presente.</p></header>{appointments.isLoading && <div className="space-y-3"><Skeleton className="h-20" /><Skeleton className="h-20" /></div>}{appointments.isError && <Alert variant="destructive"><CalendarClock className="size-4" /><AlertTitle>Agenda indisponível</AlertTitle><AlertDescription><Button variant="outline" className="mt-3" onClick={() => appointments.refetch()}><RefreshCw className="mr-2 size-4" />Atualizar</Button></AlertDescription></Alert>}{appointments.data?.length === 0 && <div className="rounded-lg border border-dashed p-8 text-center"><CalendarClock className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-semibold">Sem agendamentos registados</p></div>}<div className="divide-y rounded-lg border bg-card">{ordered.map((item) => <article key={item.id} className="flex flex-col gap-4 p-4 xsm:flex-row xsm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.serviceName || item.departmentName || 'Atendimento municipal'}</p><Badge variant="outline">{item.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.appointmentNumber} · {item.startTime ? new Date(item.startTime).toLocaleString('pt-MZ') : 'Horário por confirmar'} · {item.locationName || item.locationCode}</p></div>{item.status === 'CONFIRMED' && <Button disabled={checkIn.isPending} onClick={() => checkIn.mutate(item.id)}><CheckCircle2 className="mr-2 size-4" />Check-in assistido</Button>}</article>)}</div>{checkIn.isError && <Alert variant="destructive"><CalendarClock className="size-4" /><AlertTitle>Check-in não concluído</AlertTitle><AlertDescription>Confirme presença, horário e estado do agendamento antes de repetir.</AlertDescription></Alert>}</div></AdminLayout>;
}
