import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { AlertCircle, Plus, RefreshCw } from 'lucide-react';
import { AdminLayout } from '@/components/admin/AdminLayout';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';
import { changeQueueStatus, createDesk, createQueue, listAdminServices, listDepartments, listQueueConfigs, type QueueConfig } from '@/features/queue-admin/queue-admin.api';

export default function AdminConfiguracaoFilas() {
  const queues = useQuery({ queryKey: ['queue-configs'], queryFn: listQueueConfigs });
  const departments = useQuery({ queryKey: ['admin-departments'], queryFn: listDepartments });
  const services = useQuery({ queryKey: ['admin-services'], queryFn: listAdminServices });
  const [name, setName] = useState(''); const [location, setLocation] = useState('BOANE'); const [departmentId, setDepartmentId] = useState(''); const [serviceId, setServiceId] = useState(''); const [mode, setMode] = useState<QueueConfig['mode']>('HYBRID');
  const [deskQueueId, setDeskQueueId] = useState(''); const [deskCode, setDeskCode] = useState(''); const [deskName, setDeskName] = useState('');
  const command = useMutation({ mutationFn: (action: () => Promise<unknown>) => action(), onSuccess: () => { queues.refetch(); setName(''); setDeskCode(''); setDeskName(''); } });
  const filteredServices = (services.data || []).filter((item) => !departmentId || item.departmentId === departmentId);
  const run = (action: () => Promise<unknown>) => command.mutate(action);
  return <AdminLayout title="Configuração de filas" subtitle="Filas e balcões de atendimento"><div className="mx-auto max-w-[1200px] space-y-7">
    <header className="border-b pb-5"><p className="text-sm font-medium text-primary">Configuração F5</p><h2 className="mt-1 text-2xl font-semibold">Como o atendimento deve funcionar?</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Configure apenas filas e balcões validados para operação municipal.</p></header>
    {(queues.isError || departments.isError || services.isError) && <Alert variant="destructive"><AlertCircle className="size-4" /><AlertTitle>Não foi possível carregar a configuração</AlertTitle><AlertDescription><Button variant="outline" className="mt-3" onClick={() => { queues.refetch(); departments.refetch(); services.refetch(); }}><RefreshCw className="mr-2 size-4" />Tentar novamente</Button></AlertDescription></Alert>}
    {(queues.isLoading || departments.isLoading || services.isLoading) && <Skeleton className="h-52" />}
    <section className="rounded-lg border bg-card p-5"><h3 className="text-lg font-semibold">Criar fila</h3><div className="mt-4 grid gap-4 tb:grid-cols-2 lg:grid-cols-3"><div className="space-y-2"><Label htmlFor="queue-name">Nome</Label><Input id="queue-name" value={name} maxLength={150} onChange={(e) => setName(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="queue-location">Código do local</Label><Input id="queue-location" value={location} maxLength={40} onChange={(e) => setLocation(e.target.value.toUpperCase())} /></div><div className="space-y-2"><Label htmlFor="queue-department">Direção</Label><select id="queue-department" className="min-h-11 w-full rounded-md border bg-background px-3 text-sm" value={departmentId} onChange={(e) => { setDepartmentId(e.target.value); setServiceId(''); }}><option value="">Selecione</option>{departments.data?.filter((item) => item.status === 'ACTIVE').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="queue-service">Serviço opcional</Label><select id="queue-service" className="min-h-11 w-full rounded-md border bg-background px-3 text-sm" value={serviceId} onChange={(e) => setServiceId(e.target.value)}><option value="">Todos da direção</option>{filteredServices.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div><div className="space-y-2"><Label htmlFor="queue-mode">Modo</Label><select id="queue-mode" className="min-h-11 w-full rounded-md border bg-background px-3 text-sm" value={mode} onChange={(e) => setMode(e.target.value as QueueConfig['mode'])}><option value="HYBRID">Agendamento e chegada livre</option><option value="APPOINTMENT_ONLY">Somente agendamento</option><option value="WALK_IN_ONLY">Somente chegada livre</option></select></div></div><Button className="mt-5" disabled={!name.trim() || !location.trim() || !departmentId || command.isPending} onClick={() => run(() => createQueue({ name: name.trim(), locationCode: location.trim(), departmentId, serviceId: serviceId || null, mode }))}><Plus className="mr-2 size-4" />Criar fila</Button></section>
    <section><h3 className="text-lg font-semibold">Filas configuradas</h3><div className="mt-3 space-y-3">{queues.data?.map((queue) => <div key={queue.id} className="rounded-lg border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{queue.name}</p><p className="mt-1 text-sm text-muted-foreground">{queue.locationCode} · {queue.desks.length} balcões</p></div><Badge variant="outline">{queue.status}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{queue.status !== 'OPEN' && <Button size="sm" variant="outline" disabled={command.isPending} onClick={() => run(() => changeQueueStatus(queue, 'OPEN'))}>Abrir fila</Button>}{queue.status === 'OPEN' && <Button size="sm" variant="outline" disabled={command.isPending} onClick={() => run(() => changeQueueStatus(queue, 'PAUSED'))}>Pausar</Button>}{queue.status !== 'CLOSED' && <Button size="sm" variant="outline" disabled={command.isPending} onClick={() => run(() => changeQueueStatus(queue, 'CLOSED'))}>Encerrar</Button>}<Button size="sm" variant="ghost" onClick={() => setDeskQueueId(queue.id)}>Adicionar balcão</Button></div>{deskQueueId === queue.id && <div className="mt-4 grid gap-3 border-t pt-4 xsm:grid-cols-2"><div className="space-y-2"><Label htmlFor={`desk-code-${queue.id}`}>Código</Label><Input id={`desk-code-${queue.id}`} value={deskCode} maxLength={30} onChange={(e) => setDeskCode(e.target.value.toUpperCase())} /></div><div className="space-y-2"><Label htmlFor={`desk-name-${queue.id}`}>Nome visível</Label><Input id={`desk-name-${queue.id}`} value={deskName} maxLength={100} onChange={(e) => setDeskName(e.target.value)} /></div><Button className="xsm:col-span-2 xsm:w-fit" disabled={!deskCode.trim() || !deskName.trim() || command.isPending} onClick={() => run(() => createDesk(queue.id, { code: deskCode.trim(), displayName: deskName.trim() }))}>Guardar balcão</Button></div>}</div>)}</div></section>
    {command.isError && <Alert variant="destructive"><AlertCircle className="size-4" /><AlertTitle>Alteração não guardada</AlertTitle><AlertDescription>Atualize os dados. Outra alteração pode ter modificado a versão da fila.</AlertDescription></Alert>}
  </div></AdminLayout>;
}
